language: objective-c
osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Ambassador.xcworkspace
    - IOS_FRAMEWORK_SCHEME="Ambassador"
    - IOS_SDK=iphonesimulator9.3
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6S"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
before_install:
  - carthage bootstrap --no-use-binaries --no-build
script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
